package com.kms.cntt.enums;

public enum NotificationType {
  USER_CREATE_SCHEDULE,
  REFEREE_JOIN_SCHEDULE,
  ADMIN_ACCEPT_SCHEDULE,
  ADMIN_CANCEL_SCHEDULE,
  USER_CANCEL_SCHEDULE,
  USER_PAYMENTED
}
